{
    "name": "La Platine - Pilotage des approvisionnements",
    "summary": "Cockpit de lecture et d'interprétation des approvisionnements",
    "version": "18.0.1.2.1",
    "category": "Inventory/Purchase",
    "author": "Dorevia",
    "license": "LGPL-3",
    "depends": [
        "stock",
        "purchase",
        "purchase_stock",
        "mrp",
    ],
    "data": [
        "security/procurement_control_groups.xml",
        "data/procurement_alert_type_data.xml",
        "security/ir.model.access.csv",
        "views/res_company_views.xml",
        "views/product_template_views.xml",
        "views/procurement_control_line_views.xml",
        "wizard/raw_material_consumption_wizard_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
